### ISSUE TITLE
Usage with `<picture>` tag loads images twice

### ISSUE THREAD

**Issue by tobimori** [johannschopplich/unlazy#43]
### Reproduction

https://github.com/tobimori/kirby-baukasten/blob/main/site/snippets/picture.php

### Describe the bug

When using unlazy with the `<picture>` tag, multiple `source` elements that each have `data-srcset` and an `img` element with the necessary `data-src` attribute, the image specified in `data-src` is downloaded before `data-srcset` which results in a duplicated download of those images.

![38291](https://github.com/johannschopplich/unlazy/assets/29142128/564fdfb7-b27c-41c4-ada4-d2ee57c8bc1e)

Some sites where I noticed this:
- https://sew-morlaix.com/
- https://www.antonsten.com/about

**Comment by johannschopplich** [comment]
Should be fixed in https://github.com/johannschopplich/unlazy/commit/f055a46f0265352fd94a4abce0a3df3fedb722a4. Can you try [v0.10.5](https://github.com/johannschopplich/unlazy/releases/tag/v0.10.5), please?

**Comment by tobimori** [comment]
Hmm, it seems like both images still get downloaded, just the other way around?
![CleanShot 2024-02-18 at 12 00 46@2x](https://github.com/johannschopplich/unlazy/assets/29142128/c1454f37-bd2a-42c2-b7a1-4ae4617fa046)

**Comment by johannschopplich** [comment]
OK, tricky. I guess we have to ignore the loading of the `<img>` altogether, if a `<source>` is present. But I'm not 100 % sure.

**Comment by tobimori** [comment]
What's interesting is, that in the Network tab, chrome specifies the origin of the request now like this:

.png -> 
![CleanShot 2024-02-18 at 12 08 00@2x](https://github.com/johannschopplich/unlazy/assets/29142128/c6078285-e6ec-491c-8c7d-2a280d1b3593)

.avif -> my `lazyLoad()` call
![CleanShot 2024-02-18 at 12 08 34@2x](https://github.com/johannschopplich/unlazy/assets/29142128/c3fe0cfd-c783-46cd-8887-8a072fb6bfea)

**Comment by johannschopplich** [comment]
Thanks, I've got an idea.

**Comment by johannschopplich** [comment]
This issue should be resolve in https://github.com/johannschopplich/unlazy/commit/2f87c359314ff392738558e98cff6d2b29ca084f… Please try [v0.11.0](https://github.com/johannschopplich/unlazy/releases/tag/v0.11.0). Thanks!

**Comment by tobimori** [comment]
Seems to be fixed, thanks!
